=== sunaoka/japanpost-international-mail/dist/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "title": "Japan Post's International Mail Service availability by country",
    "items": {
        "type": "object",
        "required": [
            "countryCode",
            "destination",
            "letterPost",
            "parcels",
            "ems",
            "restrictions",
            "notification"
        ],
        "properties": {
            "countryCode": {
                "type": "string",
                "title": "Country code (ISO 3166-1 Alpha-2 and assigned by Japan Post)"
            },
            "destination": {
                "type": "string",
                "title": "Destination"
            },
            "letterPost": {
                "type": "object",
                "title": "Letter-post",
                "required": [
                    "air",
                    "sal",
                    "surface"
                ],
                "properties": {
                    "air": {
                        "type": "string",
                        "title": "Letter-post (Air)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "sal": {
                        "type": "string",
                        "title": "Letter-post (SAL)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "surface": {
                        "type": "string",
                        "title": "Letter-post (Surface)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    }
                }
            },
            "parcels": {
                "type": "object",
                "title": "Parcels",
                "required": [
                    "air",
                    "sal",
                    "surface"
                ],
                "properties": {
                    "air": {
                        "type": "string",
                        "title": "Parcels (Air)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "sal": {
                        "type": "string",
                        "title": "Parcels (SAL)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "surface": {
                        "type": "string",
                        "title": "Parcels (Surface)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    }
                }
            },
            "ems": {
                "type": "string",
                "title": "EMS",
                "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
            },
            "restrictions": {
                "type": "object",
                "title": "Restrictions, and Delays in Japan",
                "required": [
                    "normal",
                    "temporary",
                    "delays"
                ],
                "properties": {
                    "normal": {
                        "type": "array",
                        "title": "Restrictions in the normal period",
                        "items": {
                            "type": "string"
                        }
                    },
                    "temporary": {
                        "type": "array",
                        "title": "Temporary restrictions caused by the novel coronavirus pandemic",
                        "items": {
                            "type": "string"
                        }
                    },
                    "delays": {
                        "type": "array",
                        "title": "Delays in Japan",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "notification": {
                "type": "string",
                "title": "Precautions concerning delivery and other matters after mail items arrive in the destination countries and territories (Contents of notification from foreign postal operators)"
            }
        }
    }
}

=== sunaoka/japanpost-international-mail/dist/en.json
[
    {
        "countryCode": "AD",
        "destination": "Andorra",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AE",
        "destination": "United Arab Emirates",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AF",
        "destination": "Afghanistan",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AG",
        "destination": "Antigua and Barbuda",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AI",
        "destination": "Anguilla",
        "letterPost": {
            "air": "not_acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "not_acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AL",
        "destination": "Albania",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AM",
        "destination": "Armenia",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AO",
        "destination": "Angola",
        "letterPost": {
            "air": "not_acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "not_acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AR",
        "destination": "Argentina",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AS",
        "destination": "American Samoa",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AT",
        "destination": "Austria",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AU",
        "destination": "Australia",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AW",
        "destination": "Aruba",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AX",
        "destination": "Ascension",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "AZ",
        "destination": "Azerbaijan",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "BA",
        "destination": "Bosnia and Herzegovina",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "acceptable"
        },
        "ems": "no_service",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "BB",
        "destination": "Barbados",
        "letterPost": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "no_service",
            "surface": "not_acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "BD",
        "destination": "Bangladesh",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "not_acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
            "normal": [],
            "temporary": [],
            "delays": []
        },
        "notification": ""
    },
    {
        "countryCode": "BE",
        "destination": "Belgium",
        "letterPost": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "parcels": {
            "air": "acceptable",
            "sal": "not_acceptable",
            "surface": "acceptable"
        },
        "ems": "acceptable",
        "restrictions": {
